# Generated by Django 6.0.6 on 2026-06-17 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('departments', '0002_alter_group_options_group_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='config_work_type_groups', related_name='work_types', to='departments.group'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload an icon image (PNG/SVG recommended, max 1MB)', null=True, upload_to='work_type_icons/'),
        ),
        migrations.CreateModel(
            name='HomePageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=list, help_text='Ordered list of 8 group IDs (null = empty slot)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home Page Layout',
                'verbose_name_plural': 'Home Page Layouts',
                'db_table': 'config_homepage_layout',
            },
        ),
    ]
