# Generated by Django 6.0.6 on 2026-06-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_worktype_groups_worktype_icon_image_homepagelayout'),
        ('departments', '0003_group_icon_image_alter_group_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='announcement_groups', help_text='Leave empty to show to all users. Select groups to target specific members.', related_name='announcements', to='departments.group'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visible_from',
            field=models.DateTimeField(blank=True, help_text='When to start showing this announcement. Null = show immediately.', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='visible_till',
            field=models.DateTimeField(blank=True, help_text='When to stop showing this announcement. Null = never expires.', null=True),
        ),
    ]
