# Generated by Django 6.0.6 on 2026-06-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_announcement_groups_announcement_visible_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('video', 'Video'), ('link', 'Link')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='announcement_attachments/%Y/%m/')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='configuration.announcement')),
            ],
            options={
                'db_table': 'announcement_attachments',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
