# Generated by Django 6.0.6 on 2026-06-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_announcementattachment'),
        ('departments', '0003_group_icon_image_alter_group_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, db_table='config_component_groups', help_text='Leave empty to apply to all groups.', related_name='components', to='departments.group')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'db_table': 'config_component',
                'ordering': ['order', 'name'],
            },
        ),
    ]
