import { useState, useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { authAPI } from '../../../api/auth'
import { groupsAPI } from '../../../api/groups'
import { useAuth } from '../../../context/AuthContext'