# Generated by Django 6.0.6 on 2026-06-09 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='group',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order on home page'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['order'], name='helpdesk_gr_order_65a692_idx'),
        ),
    ]
