# Generated by Django 6.0.6 on 2026-06-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_group_options_group_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload a group icon image (PNG/SVG recommended, max 1MB)', null=True, upload_to='group_icons/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
