# Generated by Django 6.0.6 on 2026-06-09 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('colour_hex', models.CharField(default='#0052CC', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'labels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=20, unique=True)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('work_type', models.CharField(choices=[('service_request', 'Service Request'), ('incident', 'Incident'), ('problem', 'Problem'), ('change_request', 'Change Request')], default='service_request', max_length=20)),
                ('components', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('reopened', 'Reopened')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('lowest', 'Lowest'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('highest', 'Highest')], db_index=True, default='medium', max_length=10)),
                ('urgency', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Locked once an agent claims the ticket. Only managers+ can override.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_group', models.ForeignKey(blank=True, help_text='Current group responsible. Changes on reassignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='departments.group')),
                ('assigned_user', models.ForeignKey(blank=True, help_text='Individual assignee. Null if ticket assigned to group inbox.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Original group. Determines ticket key prefix. Never changes.', on_delete=django.db.models.deletion.PROTECT, related_name='originated_tickets', to='departments.group')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_labels', to='tickets.label')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_labels', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_labels',
            },
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('blocks', 'Blocks'), ('blocked_by', 'Is Blocked By'), ('relates_to', 'Relates To'), ('duplicates', 'Duplicates'), ('cloned_by', 'Is Cloned By')], default='relates_to', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_links', to=settings.AUTH_USER_MODEL)),
                ('source_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_links', to='tickets.ticket')),
                ('target_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_links', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_links',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_status_fbbf05_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_group'], name='tickets_assigne_57a9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_user'], name='tickets_assigne_a67ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reporter'], name='tickets_reporte_23ff80_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['group'], name='tickets_group_i_82ba0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_created_ed60df_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_locked'], name='tickets_is_lock_f20808_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets_priorit_668695_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'assigned_group'], name='tickets_status_d5a84d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_group', 'created_at'], name='tickets_assigne_3bf619_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['ticket', 'created_at'], name='comments_ticket__68f46a_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='comments_author__25752a_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['ticket'], name='attachments_ticket__43ed4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketlabel',
            unique_together={('ticket', 'label')},
        ),
        migrations.AddIndex(
            model_name='ticketlink',
            index=models.Index(fields=['source_ticket'], name='ticket_link_source__1b4560_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketlink',
            index=models.Index(fields=['target_ticket'], name='ticket_link_target__00152c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketlink',
            unique_together={('source_ticket', 'target_ticket', 'relationship')},
        ),
    ]
