# Generated by Django 6.0.6 on 2026-06-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_group_options_group_order_and_more'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='label_groups', related_name='labels', to='departments.group'),
        ),
    ]
