# Generated by Django 6.0.6 on 2026-06-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ticket_created', 'Ticket Created'), ('mention', 'Mention'), ('assignment', 'Assignment'), ('status_change', 'Status Change'), ('comment', 'Comment'), ('escalation', 'Escalation'), ('reassignment', 'Reassignment'), ('resolution', 'Resolution'), ('reopened', 'Reopened')], db_index=True, max_length=20),
        ),
    ]
