# Generated by Django 6.0.6 on 2026-06-20 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationdelivery'),
        ('tickets', '0002_label_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketInterestedParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('reporter', 'Reporter'), ('assignee', 'Assignee'), ('reassigned', 'Reassigned the Ticket'), ('commented', 'Commented'), ('mentioned', 'Mentioned')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_parties', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_interested_parties',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'user'], name='ticket_inte_ticket__6be32c_idx')],
                'unique_together': {('ticket', 'user', 'reason')},
            },
        ),
    ]
