# Generated by Django 6.0.6 on 2026-06-20 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_announcementattachment'),
        ('departments', '0003_group_icon_image_alter_group_email'),
        ('notifications', '0004_ticketinterestedparty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('user', 'Specific User'), ('group', 'Specific Group')], max_length=10)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push')], max_length=10)),
                ('event_type', models.CharField(blank=True, choices=[('ticket_created', 'Ticket Created'), ('mention', 'Mention'), ('assignment', 'Assignment'), ('status_change', 'Status Change'), ('comment', 'Comment'), ('escalation', 'Escalation'), ('reassignment', 'Reassignment'), ('resolution', 'Resolution'), ('reopened', 'Reopened')], help_text='Leave blank to apply to all event types.', max_length=20, null=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='False = suppress this channel for this scope/event/transition. True = explicitly re-enable (useful to override a broader suppressing rule).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules_created', to=settings.AUTH_USER_MODEL)),
                ('from_status', models.ForeignKey(blank=True, help_text='Optional. Only used for status_change rules targeting a specific transition.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules_from', to='configuration.status')),
                ('group', models.ForeignKey(blank=True, help_text='Set when scope = group. Leave blank when scope = user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='departments.group')),
                ('to_status', models.ForeignKey(blank=True, help_text='Optional. Only used for status_change rules targeting a specific transition.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules_to', to='configuration.status')),
                ('user', models.ForeignKey(blank=True, help_text='Set when scope = user. Leave blank when scope = group.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_rules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope', 'user'], name='notificatio_scope_91dbe3_idx'), models.Index(fields=['scope', 'group'], name='notificatio_scope_e02965_idx'), models.Index(fields=['channel', 'event_type'], name='notificatio_channel_a8dcda_idx')],
            },
        ),
    ]
